export default {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  COMPLETE_ALL: 'COMPLETE_ALL',
  DELETE_COMPLETED: 'DELETE_COMPLETED',
  CHANGE_FILTER: 'CHANGE_FILTER',
  CHANGE_EDITED_ID: 'CHANGE_EDITED_ID',
};